name: WakaTime infographic update
custom_title: Monthly Coding Time Distribution 

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: Update repo README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: last_30_days
          
